language: ruby
rvm:
  - 2.5.3
  - 2.4.5
  - 2.3.8

env:
  - ETCD_VERSION=v3.1.20
  - ETCD_VERSION=v3.2.25
# v3.3.10 is not working for whatever reason (at least in travis, spec passes
# locally for me)
#  - ETCD_VERSION=v3.3.10

install:
    - bundle install
    - bundle exec rake download-etcd
    - export PATH="$(dirname $(find /tmp -name 'etcd')):$PATH"

script: bundle exec rspec
