# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: annotations.proto

require 'google/protobuf'

#require 'http_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
end

module Google
  module Api
  end
end
