# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "authpb.User" do
    optional :name, :bytes, 1
    optional :password, :bytes, 2
    repeated :roles, :string, 3
  end
  add_message "authpb.Permission" do
    optional :permType, :enum, 1, "authpb.Permission.Type"
    optional :key, :bytes, 2
    optional :range_end, :bytes, 3
  end
  add_enum "authpb.Permission.Type" do
    value :READ, 0
    value :WRITE, 1
    value :READWRITE, 2
  end
  add_message "authpb.Role" do
    optional :name, :bytes, 1
    repeated :keyPermission, :message, 2, "authpb.Permission"
  end
end

module Authpb
  User = Google::Protobuf::DescriptorPool.generated_pool.lookup("authpb.User").msgclass
  Permission = Google::Protobuf::DescriptorPool.generated_pool.lookup("authpb.Permission").msgclass
  Permission::Type = Google::Protobuf::DescriptorPool.generated_pool.lookup("authpb.Permission.Type").enummodule
  Role = Google::Protobuf::DescriptorPool.generated_pool.lookup("authpb.Role").msgclass
end
