# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: v3lock.proto for package 'v3lockpb'

require 'grpc'
require_relative 'v3lock_pb'

module V3lockpb
  module Lock
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'v3lockpb.Lock'

      # Lock acquires a distributed shared lock on a given named lock.
      rpc :Lock, LockRequest, LockResponse
      # Unlock takes a key returned by Lock and releases the hold on lock.
      rpc :Unlock, UnlockRequest, UnlockResponse
    end

    Stub = Service.rpc_stub_class
  end
end
