# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v3lock.proto

require 'google/protobuf'

require_relative 'annotations_pb'
require_relative 'rpc_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "v3lockpb.LockRequest" do
    optional :name, :bytes, 1
    optional :lease, :int64, 2
  end
  add_message "v3lockpb.LockResponse" do
    optional :header, :message, 1, "etcdserverpb.ResponseHeader"
    optional :key, :bytes, 2
  end
  add_message "v3lockpb.UnlockRequest" do
    optional :key, :bytes, 1
  end
  add_message "v3lockpb.UnlockResponse" do
    optional :header, :message, 1, "etcdserverpb.ResponseHeader"
  end
end

module V3lockpb
  LockRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("v3lockpb.LockRequest").msgclass
  LockResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("v3lockpb.LockResponse").msgclass
  UnlockRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("v3lockpb.UnlockRequest").msgclass
  UnlockResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("v3lockpb.UnlockResponse").msgclass
end
