# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kv.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "mvccpb.KeyValue" do
    optional :key, :bytes, 1
    optional :create_revision, :int64, 2
    optional :mod_revision, :int64, 3
    optional :version, :int64, 4
    optional :value, :bytes, 5
    optional :lease, :int64, 6
  end
  add_message "mvccpb.Event" do
    optional :type, :enum, 1, "mvccpb.Event.EventType"
    optional :kv, :message, 2, "mvccpb.KeyValue"
    optional :prev_kv, :message, 3, "mvccpb.KeyValue"
  end
  add_enum "mvccpb.Event.EventType" do
    value :PUT, 0
    value :DELETE, 1
  end
end

module Mvccpb
  KeyValue = Google::Protobuf::DescriptorPool.generated_pool.lookup("mvccpb.KeyValue").msgclass
  Event = Google::Protobuf::DescriptorPool.generated_pool.lookup("mvccpb.Event").msgclass
  Event::EventType = Google::Protobuf::DescriptorPool.generated_pool.lookup("mvccpb.Event.EventType").enummodule
end
